services:
  - type: web
    name: my-bot
    env:
      - TELEGRAM_TOKEN: your-bot-token-here
    build:
      context: .
      dockerfile: Dockerfile
    port: 8443
    healthcheck:
      http:
        path: /
        port: 8443
      initial_delay: 30
      timeout: 5
      retries: 5
    env_vars:
      - TELEGRAM_TOKEN
    scaling:
      minInstances: 1
      maxInstances: 1
