services:  
  - type: web    
    name: hamster-generator    
    env: python
    buildCommand: "pip install -r requirements.txt"   
    buildCommand: "pip install python-telegram-bot"   
    startCommand: "python bot.py"  
     plan: free
    deploy:
      branch: main
