services:
- type: web
  name: hamsterkombat
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  envVars:
    - key: FLASK_APP
      value: app.py
    - key: FLASK_ENV
      value: production
