services:
  - type: web
    name: hamsterkombat
    env:
      - FLASK_APP=app
      - FLASK_ENV=production
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py --setup mysetup"
    port: 8080
