build:
  command: pip install -r requirements.txt
  env:
    - PYTHON_VERSION=3.9.7

start:
  command: gunicorn main:app --worker-class sync --workers 1 --timeout 120
  port: 8080
  env:
    - PYTHON_VERSION=3.9.7