services:
  - type: web
    name: my-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py --setup mysetup"
    port: 8080
    healthCheck:
      url: /
      interval: 10s
      timeout: 5s
      retries: 3
